ARG BASE=node:20.18.0
FROM ${BASE} AS base

WORKDIR /app

# Install dependencies (this step is cached as long as the dependencies don't change)
COPY package.json pnpm-lock.yaml ./

RUN corepack enable pnpm && pnpm install

# Copy the rest of your app's source code
COPY . .

# Expose the port the app runs on
EXPOSE 5173

# Production image
FROM base AS floraa-production

# Define environment variables for Floraa.dev
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG GITHUB_CALLBACK_URL
ARG OPENAI_API_KEY
ARG ANTHROPIC_API_KEY
ARG GOOGLE_GENERATIVE_AI_API_KEY
ARG DATABASE_URL
ARG SESSION_SECRET
ARG NODE_ENV=production
ARG VITE_LOG_LEVEL=info
ARG OLLAMA_API_BASE_URL
ARG DEFAULT_NUM_CTX

ENV WRANGLER_SEND_METRICS=false \
    GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID} \
    GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET} \
    GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL} \
    OPENAI_API_KEY=${OPENAI_API_KEY} \
    ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY} \
    GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY} \
    DATABASE_URL=${DATABASE_URL} \
    SESSION_SECRET=${SESSION_SECRET} \
    NODE_ENV=${NODE_ENV} \
    VITE_LOG_LEVEL=${VITE_LOG_LEVEL} \
    OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL} \
    DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX}

# Pre-configure wrangler to disable metrics
RUN mkdir -p /root/.config/.wrangler && \
    echo '{"enabled":false}' > /root/.config/.wrangler/metrics.json

RUN pnpm run build

CMD [ "pnpm", "run", "dockerstart"]

# Development image
FROM base AS floraa-development

# Define the same environment variables for development
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG GITHUB_CALLBACK_URL
ARG OPENAI_API_KEY
ARG ANTHROPIC_API_KEY
ARG GOOGLE_GENERATIVE_AI_API_KEY
ARG DATABASE_URL
ARG SESSION_SECRET
ARG NODE_ENV=development
ARG VITE_LOG_LEVEL=debug
ARG OLLAMA_API_BASE_URL
ARG DEFAULT_NUM_CTX

ENV GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID} \
    GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET} \
    GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL} \
    OPENAI_API_KEY=${OPENAI_API_KEY} \
    ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY} \
    GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY} \
    DATABASE_URL=${DATABASE_URL} \
    SESSION_SECRET=${SESSION_SECRET} \
    NODE_ENV=${NODE_ENV} \
    VITE_LOG_LEVEL=${VITE_LOG_LEVEL} \
    OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL} \
    DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX}

RUN mkdir -p /app/run
CMD pnpm run dev --host
